version: "3.8"

services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/tweeter/client
  #   command: yarn dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    links:
      - postgres
    env_file:
      - server/.env
    volumes:
      # - ./server:/home/app/server
      # - serverNM:/home/app/server/node_modules
      - ./server:/home/app/server/dev
      - serverNM:/home/app/server/dev/node_modules/


  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=musagy
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
  serverNM:
