version: "3.8"

services:
  client:
    build: ./client
      # context: .
      # dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./client:/tweeter/client
    # command: yarn dev

  server:
    build: ./server
      # context: .
      # dockerfile: ./server/Dockerfile
    ports:
      - "4001:4001"
    # volumes:
    #   - ./server:/tweeter/server
    # command: yarn dev

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=musagy
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
